title: GasFlux
description: An open-source package for analysing gas emissions data
theme: just-the-docs

url: https://gasflux.github.io

aux_links:
  Template Repository: https://github.com/gasflux/gasflux.github.io
